### ISSUE TITLE
Clang thinks a variable might be uninitialized

### ISSUE THREAD

**Issue by t0ny-peng** [eclipse-iceoryx/iceoryx#905]
## Required information

**Operating system:**
Ubuntu 20.04 LTS

**Compiler version:**
CLang 12.0

**Observed result or behaviour:**
Clang thinks [this](https://github.com/t0ny-peng/iceoryx/blob/3aa0050818197bf3d7d0a9e0fe71be0bb4e44cc5/iceoryx_utils/test/stresstests/benchmark_optional_and_expected/benchmark_optional_and_expected.cpp#L136) variable might be uninitialized.

```c++
    uint64_t maybeValue;
    uint64_t returnValue = complexErrorValueImpl(maybeValue);
    if (returnValue == 0)
    {
        globalCounter += maybeValue;
    }
    else
    {
        globalCounter -= returnValue;
    }
```

```
/builds/XXX/XXX/iceoryx/iceoryx_utils/test/stresstests/benchmark_optional_and_expected/benchmark_optional_and_expected.cpp:140:23: error: ‘maybeValue’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
         globalCounter += maybeValue;
         ~~~~~~~~~~~~~~^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```
zed result or behaviour:**
What do you expect to happen?

**Conditions where it occurred / Performed steps:**
Just build with Clang 12.0

I'll push a fix.
