### PR TITLE
iox-#905 libcxx support for clang

### LINKED ISSUE #905: Clang thinks a variable might be uninitialized
## Required information

**Operating system:**
Ubuntu 20.04 LTS

**Compiler version:**
CLang 12.0

**Observed result or behaviour:**
Clang thinks [this](https://github.com/t0ny-peng/iceoryx/blob/3aa0050818197bf3d7d0a9e0fe71be0bb4e44cc5/iceoryx_utils/test/stresstests/benchmark_optional_and_expected/benchmark_optional_and_expected.cpp#L136) variable might be uninitialized.

```c++
    uint64_t maybeValue;
    uint64_t returnValue = complexErrorValueImpl(maybeValue);
    if (returnValue == 0)
    {
        globalCounter += maybeValue;
    }
    else
    {
        globalCounter -= returnValue;
    }
```

```
/builds/XXX/XXX/iceoryx/iceoryx_utils/test/stresstests/benchmark_optional_and_expected/benchmark_optional_and_expected.cpp:140:23: error: ‘maybeValue’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
         globalCounter += maybeValue;
         ~~~~~~~~~~~~~~^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```
zed result or behaviour:**
What do you expect to happen?

**Conditions where it occurred / Performed steps:**
Just build with Clang 12.0

I'll push a fix.

### PR DESCRIPTION
**Pull request by dkroenke**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CHANGELOG.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #905
- Relates to #878

### CODE REVIEW

File: iceoryx_hoofs/test/stresstests/benchmark_optional_and_expected/benchmark_optional_and_expected.cpp [hunk 1]
```diff
@@ -88,7 +88,7 @@ bool popFromFiFoImpl(uint64_t& value)
 
 void popFromFiFo()
 {
-    uint64_t maybeValue;
+    uint64_t maybeValue{0U};
```
Comment (mossmaurice) [inline iceoryx_hoofs/test/stresstests/benchmark_optional_and_expected/benchmark_optional_and_expected.cpp:91]: :heart:

**Review by mossmaurice — APPROVED** [review]
LGTM
